# Generated by Django 5.2 on 2025-04-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_exemplar', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('data_emprestimo', models.DateField()),
                ('data_devolucao_prevista', models.DateField()),
                ('data_devolucao_real', models.DateField(null=True)),
            ],
            options={
                'db_table': 'Emprestimos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_livro', models.IntegerField()),
                ('codigo_barras', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Exemplares',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=20, null=True, unique=True)),
                ('ano_publicacao', models.IntegerField(null=True)),
                ('editora', models.CharField(max_length=100, null=True)),
                ('quantidade_total', models.IntegerField()),
                ('quantidade_disponivel', models.IntegerField()),
                ('descricao', models.TextField(null=True)),
                ('numero_paginas', models.IntegerField(null=True)),
                ('genero', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'Livros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('telefone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Usuarios',
                'managed': False,
            },
        ),
    ]
